Repository sschipke/movie-tracker, pull requests merged in 2019-10, with the labels that each got.

#5 Display MovieCards after updating redux store state
  src/actions/index.js
  src/components/App.js
  src/components/Login/Login.js
  src/components/Main/Main.css
  src/components/Main/Main.js
  src/components/MovieCard/MovieCard.css
  src/components/MovieCard/MovieCard.js
  src/components/MovieList/MovieList.css
  src/components/MovieList/MovieList.js
  src/reducers/index.js
  src/reducers/movies.js
  src/util/apiCalls.js
Labels: MVP

#21 Form validation/error handling for loggin in users
  src/actions/index.js
  src/components/Login/Login.css
  src/components/Login/Login.js
  src/images/form-background.jpg
  src/reducers/user.js
  src/util/apiCalls.js
Labels: Error Handling, MVP

#24 Favorites
  src/actions/index.js
  src/components/App.js
  src/components/Login/Login.js
  src/reducers/favorites.js
  src/reducers/index.js
  src/util/apiCalls.js
Labels: MVP

#25 Testing
  package.json
  src/components/App.js
  src/components/App.test.js
  src/components/MovieCard/MovieCard.test.js
  src/components/MovieCard/__snapshots__/MovieCard.test.js.snap
  src/components/__snapshots__/App.test.js.snap
Labels: testing

#26 Implement MoviePage component and links from individual cards.
  src/components/App.js
  src/components/MovieCard/MovieCard.js
  src/components/MoviePage/MoviePage.css
  src/components/MoviePage/MoviePage.js
Labels: MVP

#30 Movie page array
  src/components/App.js
  src/util/apiCalls.js
Labels: MVP

#35 Fav container
  DOCS/MovieSnagLogo.svg
  public/favicon.ico
  public/logo192.png
  public/logo512.png
  src/components/App.js
  src/components/Favorites/Favorites.css
  src/components/Favorites/Favorites.js
  src/components/Main/Main.css
  src/components/MovieList/MovieList.css
  src/components/Nav/Nav.css
  src/components/Nav/Nav.js
  src/images/MovieSnagLogo.png
Labels: MVP

#36 Render fave cards
  src/components/MovieCard/MovieCard.css
  src/components/MovieCard/MovieCard.js
  src/images/star.svg
Labels: enhancement

#38 Fav container
  DOCS/MovieSnagLogo.svg
  src/components/Favorites/Favorites.js
  src/components/MovieCard/MovieCard.css
  src/components/Nav/Nav.css
  src/components/Nav/Nav.js
  src/images/star.svg
Labels: MVP

#41 Testing
  src/actions/actions.test.js
  src/components/App.test.js
  src/components/MovieCard/MovieCard.test.js
  src/components/MovieCard/__snapshots__/MovieCard.test.js.snap
  src/components/__snapshots__/App.test.js.snap
Labels: testing

#42 Ss testing
  src/components/Login/Login.test.js
  src/components/Nav/Nav.js
  src/components/Nav/Nav.test.js
  src/components/Nav/__snapshots__/Nav.test.js.snap
  src/reducers/reducers.test.js
  src/util/apiCalls.js
  src/util/apiCalls.test.js
Labels: testing

#46 Update testing Proptypes without errors/warnings
  src/components/MovieList/MovieList.test.js
  src/components/MovieList/__snapshots__/MovieList.test.js.snap
  src/containers/Favorites/Favotites.test.js
  src/containers/Favorites/__snapshots__/Favotites.test.js.snap
  src/containers/Main/Main.test.js
  src/containers/Main/__snapshots__/Main.test.js.snap
Labels: testing

#52 Linting
  package-lock.json
  package.json
  src/.eslintrc
  src/actions/index.js
  src/components/MovieList/MovieList.js
  src/components/MoviePage/MoviePage.js
  src/containers/App/App.js
  src/containers/Favorites/Favorites.js
  src/containers/Login/Login.js
  src/containers/Main/Main.js
  src/containers/MovieCard/MovieCard.js
  src/containers/Nav/Nav.js
  src/reducers/favorites.js
  src/reducers/index.js
  src/reducers/movies.js
  src/reducers/upcomingMovies.js
  src/reducers/user.js
Labels: MVP
